# Generated by Django 4.2 on 2023-04-18 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0008_alter_transaction_format'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='type',
            field=models.CharField(choices=[('digital resources', 'Digital Resources'), ('directional', 'Directional'), ('information services', 'Information Services'), ('known item requests', 'Known Item Requests'), ('tech help', 'Tech Help')], max_length=64),
        ),
    ]
